version: '3'
services: 
    ec2_server:
        build: .docker/ubuntu_server
        container_name: ubuntu_server
        restart: always
        tty: true
        ports: 
            - "80:80"
        volumes: 
            - ./EC2_SERVER:/var/www
        networks: 
            personal:
                aliases:
                    - api-desafio.localhost
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost"]
            interval: 1m30s
            timeout: 10s
            retries: 3
    memcached:
        image: 'memcached:1.6.6'
        ports: 
            - "11211:11211"
        networks:
            - personal
    memcached2:
        image: 'memcached:1.6.6'
        ports: 
            - "11212:11211"
        networks:
            - personal
networks: 
    personal:
        driver: bridge